name: Auto Update Reject Rules

on:
  push:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Build Script
        run: python build.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add reject_rules.json
          git diff-index --quiet HEAD || git commit -m "Auto-update reject_rules.json"
          git push
