name: Proxy Sync

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4

      - name: Download, filter and format proxies
        run: |
          > raw_combined.txt
          
          curl -sL "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/BLACK_SS%2BAll_RUS.txt" >> raw_combined.txt
          echo "" >> raw_combined.txt
          
          curl -sL "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/BLACK_VLESS_RUS.txt" >> raw_combined.txt
          echo "" >> raw_combined.txt
          
          curl -sL "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/main/BLACK_VLESS_RUS_mobile.txt" >> raw_combined.txt
          echo "" >> raw_combined.txt
          
          grep -v -i -E "Anycast-IP|fixnet|fixcord" raw_combined.txt > filtered.txt
          
          sort -u filtered.txt | grep -E -v "^$" > clean.txt
          
          mkdir -p data
          
          echo "proxies:" > data/proxy.yaml
          while IFS= read -r line; do
            echo "  - $line" >> data/proxy.yaml
          done < clean.txt
          
          rm raw_combined.txt filtered.txt clean.txt

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          
          git add data/proxy.yaml
          git commit -m "update proxies" || echo "Nothing to commit"
          git push origin HEAD:${{ github.ref_name }}
